use_default_settings:
  engines:
    keep_only:
      - google
      - duckduckgo
      - brave
      - startpage
      - dictzone
      - currency
      - wikipedia
      - devicons
      - lucide
      - material icons
      - bing images
      - google images
      - duckduckgo images
      - openverse
      - unsplash
      - wikicommons.images
      - duckduckgo videos
      - youtube
      - startpage news
      - duckduckgo news
      - soundcloud
      - apple app store
      - google play apps
      - apple maps
      - openstreetmap
      - photon
      - reddit
      - openmeteo
      - duckduckgo weather

general:
  instance_name: "SearXNG"

server:
  limiter: false
  image_proxy: false

search:
  safe_search: 1
  favicon_resolver: "duckduckgo"
  autocomplete: "duckduckgo"
  default_lang: "auto"
  formats:
    - html
    - json

ui:
  default_locale: "en"

outgoing:
  default_doi_resolver: "doi.org"

engines:
  - name: google
    disabled: false
    inactive: false

  - name: duckduckgo
    disabled: false

  - name: brave
    disabled: false

  - name: startpage
    disabled: false

  - name: dictzone
    disabled: false

  - name: currency
    disabled: false

  - name: wikipedia
    disabled: false

  - name: devicons
    disabled: false

  - name: lucide
    disabled: false

  - name: material icons
    disabled: false

  - name: bing images
    disabled: false

  - name: google images
    disabled: false
    inactive: false

  - name: duckduckgo images
    disabled: false

  - name: openverse
    disabled: false

  - name: unsplash
    disabled: false

  - name: wikicommons.images
    disabled: false

  - name: duckduckgo videos
    disabled: false

  - name: youtube
    disabled: false

  - name: startpage news
    disabled: false

  - name: duckduckgo news
    disabled: false

  - name: soundcloud
    disabled: false

  - name: apple app store
    disabled: false

  - name: google play apps
    disabled: false

  - name: apple maps
    disabled: false

  - name: openstreetmap
    disabled: false

  - name: photon
    disabled: false

  - name: reddit
    disabled: false

  - name: openmeteo
    disabled: false

  - name: duckduckgo weather
    disabled: false
